services:
  server:
    build:
      context: ./server
      dockerfile: ../Dockerfile
      args:
        - PROJECT=server
    ports:
      - "20001:8080"

  proxy:
    build:
      context: ./proxy
      dockerfile: ../Dockerfile
      args:
        - PROJECT=proxy
    depends_on:
      - server
    ports:
      - "20002:8080"

  client:
    build:
      context: ./client
      dockerfile: ../Dockerfile
      args:
        - PROJECT=client
    depends_on:
      - proxy
    command: --addr http://proxy


  httptransfer:
    build:
      context: ./httptransfer
      dockerfile: ../Dockerfile
      args:
        - PROJECT=httptransfer
    volumes:
      - "./httptransfer/data/:/data/"
    ports:
      - "20003:8080"
    command: --get /data/get_file --post /data/post_file
