on:
  push:
    tags:
      - '**/v[0-9]+.[0-9]+'

jobs:
  docker-push:
    runs-on: ubuntu-latest
    steps:
      - name: Clone git Repository
        uses: actions/checkout@v3
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: lucasegp
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build Image
        run:
          bash ./.github/scripts/build.sh
      
      - name: Push Image
        run:
          bash ./.github/scripts/push.sh
